### ISSUE TITLE
ionic.bundle.js:17763 ReferenceError: cordova is not defined

### ISSUE THREAD

**Issue by sleeperagent** [petermetz/cordova-proximity-quickstart#10]
Hello!

I followed your setup instructions for this eample, but unfortunately I'm getting this error ionic.bundle.js:17763 ReferenceError: cordova is not defined" in the browser console whenever I click the monitoring and ranging icons in the menu.

I seem to be doing something wrong... Any advice?

**Comment by RAMDdFLEET** [comment]
You won't get any issues when you run it on your phone. Internally app has used a cordova plugin which is specially written for mobile. So you cannot expect always for it to work in your browser.

**Comment by petermetz** [comment]
Hi @sleeperagent 

Sorry for the late response. The error you are experiencing is related to your project/Cordova setup (or you are in fact running the code in an incompatible browser)

I'd suggest trying to fix that first because it looks like your Cordova js library is not being loaded at all.
