### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by neilyoung** [petermetz/cordova-proximity-quickstart#11]
npm WARN cordova-proximity-quickstart@1.0.0 No repository field.
npm WARN cordova-proximity-quickstart@1.0.0 No license field.
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.1.1
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE

npm ERR! node-sass@0.9.6 install: `node build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@0.9.6 install script 'node build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/me/Documents/Ionic/cordova-proximity-quickstart/npm-debug.log

**Comment by neilyoung** [comment]
Well, removed dependency gulp-sass from package.json. Works now

**Comment by neilyoung** [comment]
But the entire app is not working on the device :( Hangs and dies "Terminated due to memory issue"
Thanks for this

**Comment by blattmann** [comment]
I was running in the same installation issue with SASS:
* MacOSX Yosemite
* latest version of NPM and Node

I changed the SASS-version in the package.json to "^2.2.0" and all went fine:

`{
  "name": "cordova-proximity-quickstart",
  "version": "1.0.0",
  "description": "Helps you get going with proximity related problems in Cordova.",
  "dependencies": {
    "gulp": "^3.5.8",
    "gulp-sass": "^1.2.0",
    "gulp-concat": "^2.2.0",
    "gulp-minify-css": "^0.3.0",
    "gulp-rename": "^1.2.0"
  },
  "devDependencies": {
    "bower": "^1.3.3",
    "gulp-util": "^2.2.14",
    "shelljs": "^0.3.0"
  }
}
`
I hope this helps ;)
