### ISSUE TITLE
iOS 11.2.6 build fail

### ISSUE THREAD

**Issue by graphicgeek** [petermetz/cordova-proximity-quickstart#13]
Ionic: 3.9.3
Cordova: 8.0.0
ios platform: 4.5.4

> Ld /Users/station5/Library/Developer/Xcode/DerivedData/Proximity-finkotlypzdxhnfjvkhuwrkzpaiu/Build/Products/Debug-iphonesimulator/Proximity.app/Proximity normal x86_64
>     cd /Users/station5/Projects/phonegap/cordova-proximity-quickstart/platforms/ios
>     export IPHONEOS_DEPLOYMENT_TARGET=9.0
>     export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
>     /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.2.sdk -L/Users/station5/Library/Developer/Xcode/DerivedData/Proximity-finkotlypzdxhnfjvkhuwrkzpaiu/Build/Products/Debug-iphonesimulator -F/Users/station5/Library/Developer/Xcode/DerivedData/Proximity-finkotlypzdxhnfjvkhuwrkzpaiu/Build/Products/Debug-iphonesimulator -filelist /Users/station5/Library/Developer/Xcode/DerivedData/Proximity-finkotlypzdxhnfjvkhuwrkzpaiu/Build/Intermediates.noindex/Proximity.build/Debug-iphonesimulator/Proximity.build/Objects-normal/x86_64/Proximity.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -mios-simulator-version-min=9.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/station5/Library/Developer/Xcode/DerivedData/Proximity-finkotlypzdxhnfjvkhuwrkzpaiu/Build/Intermediates.noindex/Proximity.build/Debug-iphonesimulator/Proximity.build/Objects-normal/x86_64/Proximity_lto.o -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -ObjC -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/station5/Library/Developer/Xcode/DerivedData/Proximity-finkotlypzdxhnfjvkhuwrkzpaiu/Build/Intermediates.noindex/Proximity.build/Debug-iphonesimulator/Proximity.build/Proximity.app.xcent /Users/station5/Library/Developer/Xcode/DerivedData/Proximity-finkotlypzdxhnfjvkhuwrkzpaiu/Build/Products/Debug-iphonesimulator/libCordova.a -lz -framework CoreBluetooth -framework CoreLocation -Xlinker -dependency_info -Xlinker /Users/station5/Library/Developer/Xcode/DerivedData/Proximity-finkotlypzdxhnfjvkhuwrkzpaiu/Build/Intermediates.noindex/Proximity.build/Debug-iphonesimulator/Proximity.build/Objects-normal/x86_64/Proximity_dependency_info.dat -o /Users/station5/Library/Developer/Xcode/DerivedData/Proximity-finkotlypzdxhnfjvkhuwrkzpaiu/Build/Products/Debug-iphonesimulator/Proximity.app/Proximity
> 
> duplicate symbol _OBJC_CLASS_$_CDVLogger in:
>     /Users/station5/Library/Developer/Xcode/DerivedData/Proximity-finkotlypzdxhnfjvkhuwrkzpaiu/Build/Intermediates.noindex/Proximity.build/Debug-iphonesimulator/Proximity.build/Objects-normal/x86_64/CDVLogger.o
>     /Users/station5/Library/Developer/Xcode/DerivedData/Proximity-finkotlypzdxhnfjvkhuwrkzpaiu/Build/Products/Debug-iphonesimulator/libCordova.a(CDVLogger.o)
> duplicate symbol _OBJC_METACLASS_$_CDVLogger in:
>     /Users/station5/Library/Developer/Xcode/DerivedData/Proximity-finkotlypzdxhnfjvkhuwrkzpaiu/Build/Intermediates.noindex/Proximity.build/Debug-iphonesimulator/Proximity.build/Objects-normal/x86_64/CDVLogger.o
>     /Users/station5/Library/Developer/Xcode/DerivedData/Proximity-finkotlypzdxhnfjvkhuwrkzpaiu/Build/Products/Debug-iphonesimulator/libCordova.a(CDVLogger.o)
> ld: 2 duplicate symbols for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by petermetz** [comment]
@graphicgeek Thanks for the report. I think this might be caused by the `CDVLogger` plugin of `cordova-ios` which introduces a conflict with the plugin's own `CDVLogger`. Watch out for the next release of the plugin where I'll rename our own `CDVLogger` class to avoid the conflict.
