### ISSUE TITLE
do you tested on android ?

### ISSUE THREAD

**Issue by davidbeijinho** [petermetz/cordova-proximity-quickstart#6]
thank you

**Comment by ibrent** [comment]
Yeah.  I built it, installed on Nexus 5 running Lollipop public and it just hangs on the initial splash screen.  No response.  I haven't tried to debug yet.

**Comment by petermetz** [comment]
@davidbeijinho @ibrent 

I just pushed some updates to make the quick start compatible with the latest version of the plugin.
Please try a clean checkout and go through the steps in the README file. I just verified this to be working, if other problems arise please open a separate issue.

Thanks,
Peter

**Comment by AndreaPravato** [comment]
I have now tested the application in Android, but if I press "Start ranging" and "Start Monitoring", nothing seems to happen
