### ISSUE TITLE
Is this application still working in Android? 

### ISSUE THREAD

**Issue by AndreaPravato** [petermetz/cordova-proximity-quickstart#8]
I have tested the application in Android, but if I press "Start ranging" and "Start Monitoring", nothing seems to happen..

**Comment by petermetz** [comment]
Hi @AndreaPravato,
Can you please post here the Android and Cordova versions you were using when this happened?

Thanks in advance

**Comment by AndreaPravato** [comment]
I am sorry, I deleted the application I was working at and I do not recall this information
